# CMPINF 2100: Homework 05

## Assignment Instructions

### Overview

This assignment is more open ended than the previous ones. You must explore three data sets using the skills you have learned up to this point in the course. The Week 05 lecture material discusses the ESSENTIAL Pandas methods methods that you must ALWAYS use when BEGINNING to explore data. You must use those methods here in this assignment. You must also use SPLIT-APPLY-COMBINE to explore if summary statistics change across grouping variables.


For each of the 3 assigned data sets you must perform the following ESSENTIAL activities:

* Display the number of rows and columns in the dataset  
* Display the names of the columns and their associated data types  
* Display the number of unique values for each column  
* Display the number of MISSING values for each column  
* Display summary statistics appropriate for the data type for each column
* Count the number of rows associated with each unique value for:
    * Non-numeric columns  
    * Numeric columns with low number of unique values  

You must also execute SPLIT-APPLY-COMBINE to summarize the data based on grouping variables. Specifically, you must group by non-numeric columns and calculate the following summary statistics:
* Calculate the total number of rows for numeric columns  
* Calculate the number of non missing rows for numeric columns
* Calculate the mean and standard deviation of numeric columns
* Calculate the standard error on the mean of numeric columns
* Calculate the number of unique values for non-numeric columns

You should consider grouping by numeric columns that have low number of unique values.


## Problem 00

You will work with the NumPy and Pandas modules in this assignment.

Import NumPy and Pandas using their commonly accepted aliases.

#### 00) - SOLUTION

In [1]:
import pandas as pd
import numpy as np

## Problem 01

Your Coursera Labs environment contains a file `hw05_prob_01.csv`.

Read in the `hw05_prob_01.csv` CSV file and assign it to the `df01` object.

Explore the `df01` object following **ALL** required actions listed previously.

You must add more code cells and markdown cells to complete this problem.

#### 01) - SOLUTION

In [3]:
df01 = pd.read_csv("hw05_prob_01.csv")
df01.head()

    A   B   C         x
0  a1  b0  C1 -6.240387
1  a1  b0  C1 -4.860661
2  a1  b0  C1 -5.066712
3  a1  b0  C1 -5.635156
4  a1  b0  C1 -4.893876

For each of the 3 assigned data sets you must perform the following ESSENTIAL activities:

* Display the number of rows and columns in the dataset  
* Display the names of the columns and their associated data types  
* Display the number of unique values for each column  
* Display the number of MISSING values for each column  
* Display summary statistics appropriate for the data type for each column
* Count the number of rows associated with each unique value for:
    * Non-numeric columns  
    * Numeric columns with low number of unique values  

You must also execute SPLIT-APPLY-COMBINE to summarize the data based on grouping variables. Specifically, you must group by non-numeric columns and calculate the following summary statistics:
* Calculate the total number of rows for numeric columns  
* Calculate the number of non missing rows for numeric columns
* Calculate the mean and standard deviation of numeric columns
* Calculate the standard error on the mean of numeric columns
* Calculate the number of unique values for non-numeric columns

You should consider grouping by numeric columns that have low number of unique values.

In [ ]:
# Display the number of rows and columns in the dataset
rows, cols = df01.shape
print(rows, " rows")
print(cols, " columns")

130  rows
4  columns

In [5]:
# Display the names of the columns and their associated data types
df01.columns

Index(['A', 'B', 'C', 'x'], dtype='object')

In [9]:
# Display the number of unique values for each column  
print("Unique values", df01["A"].unique())
print("Number of unique values", df01["A"].nunique())

Unique values ['a1' 'a2']
Number of unique values 2

In [12]:
# Display the number of MISSING values for each column
df01.isna().sum()

A    0
B    0
C    0
x    0
dtype: int64

In [13]:
# Display summary statistics appropriate for the data type for each column
df01.describe()

                x
count  130.000000
mean     2.155995
std      6.015095
min     -7.185043
25%     -0.715064
50%      0.828413
75%      4.375242
max     15.382198

In [20]:
#  Count the number of rows associated with each unique value for:
#    * Non-numeric columns  
#    * Numeric columns with low number of unique values  
for col in df01.select_dtypes(exclude='number').columns:
    print(f"\n{col}:")
    print(df01[col].value_counts())

A:
A
a1    68
a2    62
Name: count, dtype: int64

B:
B
b1    78
b0    52
Name: count, dtype: int64

C:
C
C2    72
C1    58
Name: count, dtype: int64

You must also execute SPLIT-APPLY-COMBINE to summarize the data based on grouping variables. Specifically, you must group by non-numeric columns and calculate the following summary statistics:
* Calculate the total number of rows for numeric columns  
* Calculate the number of non missing rows for numeric columns
* Calculate the mean and standard deviation of numeric columns
* Calculate the standard error on the mean of numeric columns
* Calculate the number of unique values for non-numeric columns

You should consider grouping by numeric columns that have low number of unique values.

In [21]:
df01.head()

    A   B   C         x
0  a1  b0  C1 -6.240387
1  a1  b0  C1 -4.860661
2  a1  b0  C1 -5.066712
3  a1  b0  C1 -5.635156
4  a1  b0  C1 -4.893876

In [ ]:
df01.groupby(['A', 'B', 'C'])['x'].count().reset_index()

    A   B   C   x
0  a1  b0  C1   7
1  a1  b0  C2  22
2  a1  b1  C1  25
3  a1  b1  C2  14
4  a2  b0  C1  11
5  a2  b0  C2  12
6  a2  b1  C1  15
7  a2  b1  C2  24

In [36]:
# Calculate the total number of rows for numeric columns
# individually
for col in df01.select_dtypes(exclude='number').columns:
    print("Grouped by columns ", col)
    print(df01.groupby(col)['x'].size())

Grouped by columns  A
A
a1    68
a2    62
Name: x, dtype: int64
Grouped by columns  B
B
b0    52
b1    78
Name: x, dtype: int64
Grouped by columns  C
C
C1    58
C2    72
Name: x, dtype: int64

In [37]:
# Calculate the number of non missing rows for numeric columns
df01.groupby('A')['x'].count()

A
a1    68
a2    62
Name: x, dtype: int64

In [39]:
df01.groupby(['A', 'B'])['x'].count().reset_index()

    A   B   x
0  a1  b0  29
1  a1  b1  39
2  a2  b0  23
3  a2  b1  39

In [45]:
# Calculate the mean and standard deviation of numeric columns
df01.groupby(['A', 'B', 'C'])['x'].agg(['mean', 'std']).reset_index()

    A   B   C       mean       std
0  a1  b0  C1  -5.497979  0.696923
1  a1  b0  C2  13.542754  0.872442
2  a1  b1  C1  -0.183137  0.654817
3  a1  b1  C2   0.818355  0.687713
4  a2  b0  C1   5.459841  0.571378
5  a2  b0  C2  -0.580973  0.382814
6  a2  b1  C1  -5.899792  0.632946
7  a2  b1  C2   2.056517  0.767123

In [47]:
# Calculate the standard error on the mean of numeric columns
df01.groupby(['A', 'B', 'C'])['x'].sem().reset_index()

    A   B   C         x
0  a1  b0  C1  0.263412
1  a1  b0  C2  0.186005
2  a1  b1  C1  0.130963
3  a1  b1  C2  0.183799
4  a2  b0  C1  0.172277
5  a2  b0  C2  0.110509
6  a2  b1  C1  0.163426
7  a2  b1  C2  0.156588

In [46]:
# Calculate the number of unique values for non-numeric columns
df01.groupby(['A', 'B', 'C'])['x'].nunique().reset_index()

    A   B   C   x
0  a1  b0  C1   7
1  a1  b0  C2  22
2  a1  b1  C1  25
3  a1  b1  C2  14
4  a2  b0  C1  11
5  a2  b0  C2  12
6  a2  b1  C1  15
7  a2  b1  C2  24

## Problem 02

Your Coursera Labs environment contains a file `hw05_prob_02.csv`.

Read in the `hw05_prob_02.csv` CSV file and assign it to the `df02` object.

Explore the `df02` object following **ALL** required actions listed previously.

You must add more code cells and markdown cells to complete this problem.

#### 02) - SOLUTION

In [ ]:
###

## Problem 03

Your Coursera Labs environment contains a file `hw05_prob_03.csv`.

Read in the `hw05_prob_03.csv` CSV file and assign it to the `df03` object.

Explore the `df03` object following **ALL** required actions listed previously.

You must add more code cells and markdown cells to complete this problem.

#### 03) - SOLUTION

In [1]:
###